### ISSUE TITLE
Add Alexa Settings APIs

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework-nodejs#239]
## I'm submitting a...
- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other

## Expected Behavior
Implement the Alexa Settings APIs to expose the device's:
- timezone
- temperature measurement unit
- distance measurement unit

https://developer.amazon.com/docs/smapi/alexa-settings-api-reference.html

## Current Behavior
Not implemented. New feature.

### Error log
none

## Your Environment

* Jovo Framework version used: 1.4.4
* Operating System: Windows 10 Pro

**Comment by jankoenig** [comment]
Thanks Mark! @aswetlow added it today, take a look at this example: https://github.com/jovotech/jovo-framework-nodejs/blob/master/examples/alexa_specific/appAlexaSettingsAPI.js

For now, we haven't integrated the getTimestampLocal() feature request (which is great!) because we don't want to add another dependency for just one feature. We're open for suggestions though!

**Comment by jankoenig** [comment]
Thanks for #240, I think a simple code example like this is a great compromise 👍
